/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloque5;

import java.awt.Image;
import java.io.File;
import static java.lang.Math.random;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel Escudero
 */
public class Galeria extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Galeria.class.getName());

    /**
     * Creates new form Galeria
     */
    
    private List<String> listaMemes;
    private Random random = new Random();
    private boolean esIconolluvia = true;
    
    public Galeria() {
        initComponents();
        cargarMemes();
        ImageIcon iconoFondo = new ImageIcon(getClass().getResource("/bloque5/fondo/fondo1.jpg"));
        Image imagenFondo = iconoFondo.getImage();

        jPanel1 = new javax.swing.JPanel() {
           
    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);
        g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
    }
};

// Establecer layout absoluto (para que los componentes se ubiquen correctamente)
jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

// Añadir el panel al contenido principal
getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 340));

// Añadir los demás componentes *después* para que queden por encima
jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 106, 353, 176));
jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 312, -1, -1));
jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 312, -1, -1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 106, 353, 176));

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 312, -1, -1));

        jButton2.setText("Icono");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 312, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 0, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void cargarMemes() {
        listaMemes = new ArrayList<>();

        String[] nombres = {"meme1.png", "meme2.jpg", "meme3.jpg"};

        for (String nombre : nombres) {
            URL recurso = getClass().getResource("/bloque5/memes/" + nombre);
            if (recurso != null) {
                listaMemes.add("/bloque5/memes/" + nombre);
            }
        }

        if (listaMemes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontraron imágenes dentro de /bloque5/memes/");
        }
    }
     
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          if (listaMemes == null || listaMemes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay memes disponibles para mostrar.");
            return;
        }

        String ruta = listaMemes.get(random.nextInt(listaMemes.size()));
        URL recurso = getClass().getResource(ruta);

        if (recurso != null) {
            ImageIcon icon = new ImageIcon(recurso);
            int ancho = jLabel1.getWidth() > 0 ? jLabel1.getWidth() : 400;
            int alto = jLabel1.getHeight() > 0 ? jLabel1.getHeight() : 250;
            Image img = icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(img));
            jLabel1.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen: " + ruta);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String nombreIcono;
        if (esIconolluvia) {
            nombreIcono = "lluvia.png";
        } else {
            nombreIcono = "sol.png";
        }
        String rutaRecurso = "/bloque5/icono/" + nombreIcono;

        URL urlIcono = getClass().getResource(rutaRecurso);

        if (urlIcono != null) {
            ImageIcon icono = new ImageIcon(urlIcono);

            Image imagenIcono = icono.getImage();

            this.setIconImage(imagenIcono);
           
            esIconolluvia = !esIconolluvia;
           
        } else {
            logger.severe("No se pudo cargar el recurso de icono: " + rutaRecurso);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Galeria().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
